/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador_FRM_MenuPrincipal;

/**
 *
 * @author Hogar
 */
public class FRM_MenuPrincipal extends javax.swing.JFrame {

    FRM_MantenimientoEstudiantes mantenimientoEstudiantes;
    Controlador_FRM_MenuPrincipal controlador_FRM_MenuPrincipal;
    public FRM_MenuPrincipal() {
        initComponents();
        this.setLocation(330,200);
        this.controlador_FRM_MenuPrincipal=new Controlador_FRM_MenuPrincipal();
        this.mantenimientoEstudiantes=new FRM_MantenimientoEstudiantes();
        agregarEventos();
    }
    
    public void agregarEventos(){
        this.jm_Salir.addActionListener(this.controlador_FRM_MenuPrincipal);
        this.jm_Estudiante.addActionListener(this.controlador_FRM_MenuPrincipal);
        this.jm_Cursos.addActionListener(this.controlador_FRM_MenuPrincipal);
        this.jm_Matricula.addActionListener(this.controlador_FRM_MenuPrincipal);
        this.jm_Reporte.addActionListener(this.controlador_FRM_MenuPrincipal);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_FondoMenuPrincipal = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jm_Sistema = new javax.swing.JMenu();
        jm_Salir = new javax.swing.JMenuItem();
        jm_Mantenimiento = new javax.swing.JMenu();
        jm_Estudiante = new javax.swing.JMenuItem();
        jm_Cursos = new javax.swing.JMenuItem();
        jm_Matricula = new javax.swing.JMenuItem();
        jm_Reporte = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(683, 435));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_FondoMenuPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bitmap.png"))); // NOI18N
        getContentPane().add(jl_FondoMenuPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jm_Sistema.setText("Sistema");

        jm_Salir.setText("Salir");
        jm_Sistema.add(jm_Salir);

        jMenuBar1.add(jm_Sistema);

        jm_Mantenimiento.setText("Mantenimiento");
        jm_Mantenimiento.setActionCommand("Estudiantes");

        jm_Estudiante.setText("Estudiantes");
        jm_Mantenimiento.add(jm_Estudiante);

        jm_Cursos.setText("Cursos");
        jm_Mantenimiento.add(jm_Cursos);

        jm_Matricula.setText("Matricula");
        jm_Mantenimiento.add(jm_Matricula);

        jm_Reporte.setText("Reporte");
        jm_Mantenimiento.add(jm_Reporte);

        jMenuBar1.add(jm_Mantenimiento);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRM_MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRM_MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRM_MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRM_MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRM_MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel jl_FondoMenuPrincipal;
    private javax.swing.JMenuItem jm_Cursos;
    private javax.swing.JMenuItem jm_Estudiante;
    private javax.swing.JMenu jm_Mantenimiento;
    private javax.swing.JMenuItem jm_Matricula;
    private javax.swing.JMenuItem jm_Reporte;
    private javax.swing.JMenuItem jm_Salir;
    private javax.swing.JMenu jm_Sistema;
    // End of variables declaration//GEN-END:variables
}
