/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador_FRM_MantenimientoCursos;

/**
 *
 * @author Hogar
 */
public class FRM_MantenimientoCursos extends javax.swing.JFrame {

   Controlador_FRM_MantenimientoCursos controlador_FRM_MantenimientoCursos;
    public FRM_MantenimientoCursos() {
        initComponents();
        setVisible(false);
        controlador_FRM_MantenimientoCursos=new Controlador_FRM_MantenimientoCursos(this);
        this.gUI_Botones1.agregarEventos1(controlador_FRM_MantenimientoCursos);
    }
    
    public String[] devolverInformacion(){
        return this.gUI_InformacionCursos1.devolverInformacion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gUI_Botones1 = new Vista.GUI_Botones();
        gUI_InformacionCursos1 = new Vista.GUI_InformacionCursos();
        jLabel1 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(gUI_Botones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 350, 90));
        getContentPane().add(gUI_InformacionCursos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 400, 160));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo 2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vista.GUI_Botones gUI_Botones1;
    private Vista.GUI_InformacionCursos gUI_InformacionCursos1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
