/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador_FRM_MantenimientoEstudiantes;



/**
 *
 * @author Hogar
 */
public class FRM_MantenimientoEstudiantes extends javax.swing.JFrame {

    Controlador_FRM_MantenimientoEstudiantes controlador_FRM_MantenimientoEstudiantes;
    public FRM_MantenimientoEstudiantes() {
        initComponents();
        setVisible(false);
        controlador_FRM_MantenimientoEstudiantes=new Controlador_FRM_MantenimientoEstudiantes(this);
        this.gUI_Botones1.agregarEventos(controlador_FRM_MantenimientoEstudiantes);
    }
    public String[] devolverInformacion()
    {
        return this.gUI_InformacionEstudiantes1.devolverInformacion();
    }
    
    public String devolverCarnet()
    {
        return this.gUI_InformacionEstudiantes1.devolverCarnet();
    }
    public String devolverNombre()
    {
        return this.gUI_InformacionEstudiantes1.devolverNombre();
    }
    public void mostrarInformacion(String[] arreglo)
    {
        this.gUI_InformacionEstudiantes1.mostrarInformacion(arreglo);
    }
    public void limpiar()
    {
        this.gUI_InformacionEstudiantes1.limpiar();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gUI_Botones1 = new Vista.GUI_Botones();
        gUI_InformacionEstudiantes1 = new Vista.GUI_InformacionEstudiantes();
        jl_Fondo = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(gUI_Botones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 195, 350, 80));
        getContentPane().add(gUI_InformacionEstudiantes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 480, 100));

        jl_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo 2.png"))); // NOI18N
        getContentPane().add(jl_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vista.GUI_Botones gUI_Botones1;
    private Vista.GUI_InformacionEstudiantes gUI_InformacionEstudiantes1;
    private javax.swing.JLabel jl_Fondo;
    // End of variables declaration//GEN-END:variables
}
