
package Vista;

import Controlador.Controlador_FRM_MantenimientoEstudiantes;


public class GUI_InformacionEstudiantes extends javax.swing.JPanel {
    
    Controlador_FRM_MantenimientoEstudiantes controlador;
    
    public GUI_InformacionEstudiantes() {
        initComponents();
    }
    public void agregarEventos(Controlador_FRM_MantenimientoEstudiantes controlador)
    {
        this.controlador=controlador;
    }
    public String[] devolverInformacion()
    {
        String arreglo[];
        arreglo =new String[2];
        arreglo[0]=this.jt_Carnet.getText();
        arreglo[1]=this.jt_NombreCompleto.getText();
        return arreglo;
    }
    
    public String devolverCarnet(){
        return this.jt_Carnet.getText();
    }
    public String devolverNombre(){
        return this.jt_NombreCompleto.getText();
    }
    public void mostrarInformacion(String[] arreglo){
        this.jt_NombreCompleto.setText(arreglo[0]);
    }
    public void limpiar()
    {
        this.jt_Carnet.setText("");
        this.jt_NombreCompleto.setText("");
    }
    public void estadoInicial(){
        this.jt_Carnet.setEnabled(true);
        this.jt_NombreCompleto.setEnabled(false);
    }
    public void deshabilitarCarnet(){
        this.jt_Carnet.setEnabled(false);
    }
    
    public void habilitarOpciones(){
        this.jt_Carnet.setEnabled(false);
        this.jt_NombreCompleto.setEnabled(true);
    }
    public void habilitarAgregar(){
        this.jt_Carnet.setEnabled(true);
        this.jt_NombreCompleto.setEnabled(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jt_Carnet = new javax.swing.JTextField();
        jt_NombreCompleto = new javax.swing.JTextField();
        jl_Fondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Carnet: ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel2.setText("Nombre completo: ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jt_Carnet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jt_CarnetKeyPressed(evt);
            }
        });
        add(jt_Carnet, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 240, -1));
        add(jt_NombreCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 240, -1));

        jl_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo 2.png"))); // NOI18N
        add(jl_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jt_CarnetKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_CarnetKeyPressed
        System.out.println("Codigo de la tecla: "+evt.getKeyCode());
        if(evt.getKeyCode()==10)
        {
            controlador.buscar();
        }
    }//GEN-LAST:event_jt_CarnetKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jl_Fondo;
    private javax.swing.JTextField jt_Carnet;
    private javax.swing.JTextField jt_NombreCompleto;
    // End of variables declaration//GEN-END:variables
}
