/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Hogar
 */
public class GUI_InformacionEstudiantes extends javax.swing.JPanel {

    /**
     * Creates new form GUI_InformacionEstudiantes
     */
    public GUI_InformacionEstudiantes() {
        initComponents();
    }
    
    public String[] devolverInformacion()
    {
        String arreglo[];
        arreglo =new String[2];
        arreglo[0]=this.jt_Carnet.getText();
        arreglo[1]=this.jt_NombreCompleto.getText();
        return arreglo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jt_Carnet = new javax.swing.JTextField();
        jt_NombreCompleto = new javax.swing.JTextField();
        jl_Fondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Carnet: ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel2.setText("Nombre completo: ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));
        add(jt_Carnet, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 240, -1));
        add(jt_NombreCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 240, -1));

        jl_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo 2.png"))); // NOI18N
        add(jl_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jl_Fondo;
    private javax.swing.JTextField jt_Carnet;
    private javax.swing.JTextField jt_NombreCompleto;
    // End of variables declaration//GEN-END:variables
}
